server:
  port: 8881
rpc:
  client:
    load-balance: random
    serialization: PROTOSTUFF
    transport: netty
    registry: nacos
    registry-addr: 127.0.0.1:8848
    timeout: 5000

# 设置控制台日志显示级别
logging:
  level:
    com.wxy.rpc: info